dist: trusty
sudo: required
language: c
addons:
  apt:
    packages:
    - pandoc
    - pandoc-citeproc
    - aspell
    - aspell-en
    - inkscape
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-font-utils
    - texlive-fonts-extra
    - texlive-latex-recommended
    - fonts-lmodern
    - lmodern
    - python
before_install:
- sudo pip install pandoc-fignos pandoc-tablenos
before_script:
- cd images ; bash convert-images.sh
script:
- cd $TRAVIS_BUILD_DIR
- ls
- ERRORS=`cat D1.3-e-Infra-Sentinel-Report.md | aspell -d en_GB -p .aspell.en.pws
  -a -c  |grep -v \* |uniq|grep -v "International Ispell Version" | wc -l`
- echo "Found $ERRORS errors"
- 'pandoc -S --filter pandoc-fignos --filter pandoc-tablenos --filter pandoc-citeproc
  --csl="institute-of-physics-numeric.csl" --variable mainfont="Lato" --variable sansfont="Lato"
  --variable monofont="Roboto" --variable fontsize=12pt --variable version=1.17.2
  --reference-odt="deliverable-template.ott" --number-sections --toc --from markdown+implicit_figures+table_captions+pipe_tables+footnotes+inline_notes+yaml_metadata_block
  D1.3-e-Infra-Sentinel-Report.md  -o D1.3-e-Infra-Sentinel-Report.odt

'
- 'pandoc -S --filter pandoc-fignos --filter pandoc-tablenos --filter pandoc-citeproc
  --csl="institute-of-physics-numeric.csl" --variable mainfont="Lato" --variable sansfont="Lato"
  --variable monofont="Roboto" --variable fontsize=12pt --variable version=1.17.2
  --number-sections --toc -t latex --from markdown+implicit_figures+table_captions+pipe_tables+footnotes+inline_notes+yaml_metadata_block
  D1.3-e-Infra-Sentinel-Report.md -o D1.3-e-Infra-Sentinel-Report.pdf

'
after_success:
before_deploy:
deploy:
  skip_cleanup: true
  provider: releases
  file:
  - D1.3-e-Infra-Sentinel-Report.odt
  - D1.3-e-Infra-Sentinel-Report.pdf
  on:
    repo: sci-gaia/D1.3e-Infrastructure-Sentinel-report
    tags: true
  api-key:
    secure: H6m2RxYwMW8QUcUecYS26hV+cedyMs4i/MJProllbgb6Lq6b1PEiD7+i7mjg1gQ0H3MYT1qLMcAh87KfwhCOwsTbaydAjcEVjENaZCfRB9e0gVghSF0MOvrh6FH0vX6KEn1nB1bI3yebFAkVOZ4y1TQlSHWJ3EaTBbegbaG25QOjJF6IA5C9BZLHFYcVvAUzVxKW78gwVJA8T845AVsByLT3LZFRnsdsGoq48AYqvo9vgNthmSc2RT0Of3koyGu1qlip8m2JAUPmWmBa+IaLKswgdx4cFAZHldlXPOJzhrplpst/upf8qoPjYkg0ij+QQ53cizUc7nKVadT0MKLeyrPbyCrNr6rvkvF8CFjiVLCl7wOUNFJLQoBLPt5C4LkV3dCgBHkrwALjXftJVvbPVW+95XSlr7FnWVOt6dvzlRrukVw1j643o6dAafx/4zpO1Acoqm0dRbk+aiurb2C7IVrnTI2EI6RiAo7zMCUVD3czHcYrJId9HC47EPsRU509GEEaRyLTV9Ln7VTJByk3UwyVPS0x5XSVkUnuC/cfGrEmuwmRU08l8lnQwpASUhX8H58DUUiaE0gtaVXvw6J549jPIrMv89Uocoenov9RB/8Io7lREjWPQhqCxrLNuU2HYFgtInUS2giIukkTjw4dWnRMYmUMJwhBaHxR5fBCKUE=
notifications:
  slack:
    secure: IY/ZbjmD3X1TY9f6rVaqhe+mjb5u4yaZzuY4ZgoAkmJffwppZzTmEcCxaX1PznIGSXCaIf7iO/9fVvN/sGvHkh8b8qB85fqIz/AdzGphF2q7kpGTzpylqLvjBqD+RoMP3luFfhhP6utXyOaw83FsRMdQs3u6KmlMQ1SdSKh/n2ct09MSoeTBrpqcZbJpk27Smi8qQqUpNQStjoak/K0ziQZRPaIgI/nH+v23PkxQmdS9j8O6Oj2Zl7HXhXKIJ7vwv9ZfVziSAZu5bjgYCXhN3hWacx2NyoB9UDtP4WCuQnAasfjyE2FBGyPJU4bp5d6DzUp44F05XQEgwoZSFAY4yRsPE3vldoP5f+BlWk3TGsp8s0OyOCP6QiOTZI6CU/ghwTImll+5Jxcq1cGUf/g09XZiku36B2Y/NDbETrguGq0L2Xn+p2e5MC1rPE7zYmB1bnSJ7dDLGOOVLkZ4BS4xyX7nkJl07XILk50K4TCJh6Oh8fIKEvfrEw+OADqQuBSufv6la+60uCpOylY+u+2CfWbbdUQK3KRccTe0qjTZIODDgmFFhLlt4g/791ellvnVn64vVNJ2uz9Uy+hOgO0wXM30LO/pZiiyRRyfcpF63lYmikAKXQhmIcCWDI8YtGFTW7WjQZ2M9kZFeAW5wbbKgt/ezLyAKe3npM99PNzG8zc=
